[build]
command = "npm run build"
publish= "/build"
base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = 'https://tinparking.netlify.app/api/*'
  to = 'http://80.78.243.244:8080/api'
  status = 200